FUNCTION(VERITAS_SET_ARCHITECTURE_PROPERTIES TARGET PARAMETER)
    SET(PROCESSOR ${CMAKE_SYSTEM_PROCESSOR})
    IF(${PROCESSOR} STREQUAL "i686")
        SET(PROCESSOR "x86")
    ENDIF()

    SET(PROCESSOR_WORD "32")

    IF(${PROCESSOR} STREQUAL "mips64"
    OR ${PROCESSOR} STREQUAL "x86_64"
    OR ${PROCESSOR} STREQUAL "arm64-v8a")
        SET(PROCESSOR_WORD "64")
    ENDIF()

    IF(NOT PARAMETER STREQUAL "INTERFACE")
        SET_PROPERTY(TARGET ${TARGET} PROPERTY "Processor" ${PLATFORM})
    ENDIF()
ENDFUNCTION()
